web:
  build: .
  command: bundle exec rails s -p 8000 -b '0.0.0.0'
  ports:
    - "8000:8000"
  links:
    - db
  volumes:
    - .:/erp
  volumes_from:
    - bundle
# worker:
#   build: .
#   command: bundle exec sidekiq -e development
#   volumes:
#     - .:/erp
#   volumes_from:
#     - bundle
#   environment:
#     RAILS_ENV: development
#   links:
#     - db
#     - redis
# redis:
#   image: redis
#   command: redis-server /usr/local/etc/redis/redis.conf
#   volumes:
#     - ./redis.conf:/usr/local/etc/redis/redis.conf
#   ports:
#     - "6380"
bundle:
  image: managementapp_web
  volumes:
    - /bundle
db:
  image: postgres
