web:
  build: .
  command: bundle exec rails s -p 5050 -b '0.0.0.0'
  ports:
    - "5050:3001"
  links:
    - db
  volumes:
    - .:/erp
  volumes_from:
    - bundle
bundle:
  image: managementapp_web
  volumes:
    - /bundle
db:
  image: postgres
